# Generated by Django 6.0.3 on 2026-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
