# Generated by Django 6.0.3 on 2026-03-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
