# Generated by Django 6.0.3 on 2026-03-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
