# Generated by Django 6.0.3 on 2026-03-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_obj',
        ),
    ]
